naming:
  appPackage: "ru.vtb.smb"
  omitWordsInPackage:
    - "feature"
  moduleNameDelimiter: "_"
  modulePackageDelimiter: "."
apiModule:
  postfix: "api"
  addPostfixToPackageName: false
  addManifest: true
  addGitIgnore: true
  buildGradleTemplate: "tools/module-templates/build-template.gradle"
  di:
    enabled: true
    addFeatureStarter: true
  presentation:
    addFeatureStarter: true
    featureStarterPackage: "presentation"
    featureStarterBaseScreen: "ru.terrakok.cicerone.android.support.SupportAppScreen"
implModule:
  postfix: "impl"
  addPostfixToPackageName: false
  addManifest: true
  addGitIgnore: true
  buildGradleTemplate: "tools/module-templates/impl-build-template.gradle"
  di:
    enabled: true
    featureScopeAnnotationClass: "ru.vtb.smb.core.PerFeature"
    screenScopeAnnotationClass: "ru.vtb.smb.core.PerScreen"
  presentation:
    enabled: true
    addFeatureStarter: true
    addViewModel: true
  ui:
    enabled: true
    baseFragmentClass: "ru.vtb.smb.core.BaseFragment"
    injectViewModel: true
